name: Michael Davis
title: Web Dev Kit
description: Personal Site
email: michael.e.davisjr@gmail.com
locale: en-Us
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]
